#index:
#    path: /
#    controller: App\Controller\DefaultController::index
kms_froala_editor:
  resource: '@KMSFroalaEditorBundle/Resources/config/routing.yml'
  prefix:   /froalaeditor

login:
  path: login
  controller: App\Controller\SecurityUserController::login
  methods: GET|POST

logout:
  path: /logout
  methods: GET